# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anh Pham
title: Ph.D. candidate in Economics
email: anh.n.q.pham.econ@gmail.com
website: https://anhpham52.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  anhpham52
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: anhpham52
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. candidate in Economics at the University of Birmingham with experience in quantitative research and DSGE modelling using MATLAB, and DYNARE. 
  My research interests focus on the topics of fiscal policy, monetary policy, and economic growth. During my research, I have shown the ability to work independently, devising and presenting monthly reports to supervisors in a timely fashion. 
  Besides, I could demonstrate strong synthesizing and writing skills.

content:
#  - title: Projects # Title for the section
 #   layout: list # Type of content section (list/text)
  #  content:
   #   - layout: top-middle
    #    title: Super awesome project
     #   link: github.com/sproogen
        # link_text: Project Website
       # additional_links:
        #  - title:  sproogen/modern-resume-theme
         #   icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
         # This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        #description: | # this will include new lines to allow paragraphs
        
  - title: Job Market Paper
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [The Economy of the United Kingdom in Pandemic (2021)](https://drive.google.com/file/d/1kde6f4A8uj6wCgbLZmDIEi0zn4WaUyJz/view?usp=sharing)
       
  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ph.D. Research
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: University of Birmingham, Department of Economics
        caption: September 2019 – Present
        description: | # this will include new lines to allow paragraphs
          
            -	Planned, organised and managed an independent research project on the business cycle and policies
          
            -	Employed DSGE model to evaluate different regimes of fiscal policies
            
            -	Applied DSGE model and Bayesian estimation to estimate the impact of shocks, and spillover effects
            
            -	Enhanced skills in time management and project management
            
            -	Consolidated ability to quickly assimilate skills in different programming languages, specialised in the use of MATLAB and DYNARE
            
            -	Proficiency in producing technical and scientific documentation using LaTeX 
            
            -	Presented results clearly and confidently to audiences in conferences and seminars

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Birmingham
        caption: September 2019 – Present 
        sub_title: Ph.D. in Economics
        description: |
          - Thesis title: “Essays on Business Cycle and Macroeconomic Policies”
          
          - Supervisors: Professor John Fender, Dr. Pei Kuang

          - Doctoral Research Scholarship of £29,280 per annum from 2019 to 2022 
          
          - HEFi Horizon Award by The Higher Education Futures institute
          
          - BBS Development Fund of £400 per annum from 2021 to 2022 
          
      - layout: left
        title: University of Birmingham
        caption: September 2016 – September 2017 
        sub_title: M.Sc. in Financial Economic
        description: |
          - Distinction degree
      - layout: left
        title: RMIT University
        caption: January 2012 – December 2015
        sub_title: B.Sc. in Economics and Finance
        description: |
          - Distinction degree
          - Awarded Golden Key Award for top academic performance
        
  - title: Working Papers
    layout: text
    content: | # this will include new lines to allow paragraphs
      - The Spillover Effects in Emerging Market: Perspective of Vietnam (2022)
      - Active and Passive Fiscal Policies in a Closed Economy (2020)
     

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
